### PR TITLE
Add IndieAuth as Plugin Dependency

### PR DESCRIPTION
**Pull request by pfefferle**
See: https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/

### CODE REVIEW

**Review by snarfed — APPROVED** [review]
LGTM!

**Comment by dshanske** [comment]
I was going to ask about backcompat, but I think we have it covered.

**Comment by pfefferle** [comment]
What do you mean with backcompat? It will be ignored by all versions below 6.5, so it should be fine.

**Comment by dshanske** [comment]
> What do you mean with backcompat? It will be ignored by all versions below 6.5, so it should be fine.

Yes, and I'm still checking for the presence of the plugin class, but I'm wondering about the long-term.

**Pull request merged**
