### PR TITLE
Store the indieauth token endpoint return as post metadata

### PR DESCRIPTION
**Pull request by lostfocus**
This should do it. ("it" being #67)

### CODE REVIEW

**Comment by snarfed** [comment]
awesome, thanks for doing this!

mind adding a test and updating the changelogs in the readmes? (you'd add a new _1.3 (unreleased)_ section.)

also, `token_data` is a pretty generic name for the post_meta key. let's call it `micropub_auth_response` instead. alternatively you could just pull out `client_id` and store it in `micropub_client_id`. i'm ok with either.

thanks again!

**Comment by lostfocus** [comment]
Yeah, for the tests I'll have to re-figure out the whole phpunit/WP test/… things first, so that might take a while. It has been a while. 👴

**Comment by snarfed** [comment]
if you want to be lazy, you don't have to set up everything to build and run tests locally. you can just add the test and push to the PR branch, and [CircleCI should run the tests automatically](https://circleci.com/gh/snarfed/wordpress-micropub) and report results there.

**Comment by lostfocus** [comment]
It was/is a good reason to get reacquainted with the whole system, but thanks. :)

**Comment by snarfed** [comment]
this is a great contribution. good discussion on the use case up front, clean code, and a test. thank you so much! and congrats on your first merge here!

**Comment by lostfocus** [comment]
Thank you very much. It was a delight.

**Pull request merged**
