### PR TITLE
Comply with WordPress Coding Standards

### PR DESCRIPTION
**Pull request by dshanske**
I've had it sitting there for nearly 3 months. Might as well.

### CODE REVIEW

**Comment by snarfed** [comment]
cool, thanks for sending!

as discussed on irc, the main additional thing this needs is docs in the readme on what these all are and how contributors can use them.

**Comment by snarfed** [comment]
quite a refactoring! looking forward to the tests too! :P

**Comment by dshanske** [comment]
If you look at the way it is designed...the argument generation is off the filter or the hook. That makes it very easy to test or even replace the parts compared to the private functions you had before.

**Comment by dshanske** [comment]
Going to close this and approach it in smaller pieces. I've also learned a lot since I wrote this with the webmentions refactoring.

**Pull request closed without merging**
