### PR TITLE
added missing return

### PR DESCRIPTION
**Pull request by pfefferle**
if missing, all entries that are rendered before are removed.

### CODE REVIEW

**Comment by pfefferle** [comment]
hmmm, it seems that circleci is not configured properly and/or uses a wrong version of PHPUnit

**Comment by snarfed** [comment]
hey, thanks for the contribution! any chance you could add a unit test for it too?

and yeah, circle has been broken for a while. not sure why, and i haven't prioritized fixing it yet.  :/

**Comment by snarfed** [comment]
here's the last circle run that succeeded: https://circleci.com/gh/snarfed/wordpress-micropub/100

**Comment by pfefferle** [comment]
I hope so ;)

**Comment by pfefferle** [comment]
I had a similar issue using travis... the fix was to install the latest PHPUnit by hand... but I have no experience with circleci... sorry :(

https://github.com/pfefferle/wordpress-webmention/blob/master/.travis.yml#L24

**Comment by snarfed** [comment]
fixed circle. feel free to rebase and retry the circle build!

**Comment by snarfed** [comment]
merging so this doesn't get forgotten. thanks again!

**Pull request merged**
