### PR TITLE
fix readme markdown...

### PR DESCRIPTION
**Pull request by pfefferle**
...update WordPress version and added update-assets workflow

### CODE REVIEW

**Comment by pfefferle** [comment]
@dshanske the first test seems broken. I tried to fix it, but I can't run the tests locally. Can you help me here?

**Comment by pfefferle** [comment]
Might be this change https://github.com/indieweb/wordpress-micropub/blob/trunk/micropub.php#L32 ? Is it a good idea to only load the classes if IndieAuth is installed? If so, we should require the classes in the tests.

**Comment by dshanske** [comment]
I have a dummy version of the file included in bootstrap...your update took it out.

**Comment by pfefferle** [comment]
Ah, I see! Re-added!

**Comment by pfefferle** [comment]
I had to change the bootstrap file, to run under osX.

**Comment by dshanske** [comment]
I didn't realize it didn't...it was the standard one generated at the time by wp-cli

**Comment by dshanske** [comment]
Wonder if I need to check every bootstrap

**Comment by pfefferle** [comment]
@dshanske can you help me fix the test, to merge the changes?

**Comment by dshanske** [comment]
I got the testing working, but there is still an error on one...I'm not sure why it never came up before. Something new that is causing the terms not to delete?

**Review by dshanske — APPROVED** [review]
The changes are good, but somehow it caused some tests to fail. I assume because of the environment changes. I can't figure out why the test to delete categories isn't working. I've tried multiple variations of it.

**Comment by pfefferle** [comment]
The text to markdown script is somehow broken... what about using the grunt scripts?

**Pull request merged**
