### PR TITLE
Switch to JSON Responses

### PR DESCRIPTION
**Pull request by dshanske**
Addresses #95 . Tested.

### CODE REVIEW

**Comment by snarfed** [comment]
thanks! this looks great. mind adding a link to https://indieauth.spec.indieweb.org/#access-token-verification to the `authorize()` method's comment? i'll happily merge after that!

**Comment by dshanske** [comment]
Will do when I get to Baltimore

**Comment by dshanske** [comment]
Done and rebased.

**Comment by snarfed** [comment]
i don't see that you changed the comment at all...?

**Comment by dshanske** [comment]
I remember doing this. Did it again. Weird.

**Comment by snarfed** [comment]
thanks!

**Pull request merged**
